//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import pluginJsxA11y from "eslint-plugin-jsx-a11y";
import pluginPromise from "eslint-plugin-promise";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";
import pluginUnusedImports from "eslint-plugin-unused-imports";

export default [
  ...tanstackConfig,
  // Must come after tanstackConfig: pulls in eslint-config-prettier to switch
  // off stylistic rules that would fight Prettier, then enables
  // `prettier/prettier` as the single formatting authority.
  eslintPluginPrettierRecommended,
  {
    files: ["**/*.{js,ts,tsx}"],
    plugins: {
      react: pluginReact,
      "react-hooks": pluginReactHooks,
      "jsx-a11y": pluginJsxA11y,
      promise: pluginPromise,
      "unused-imports": pluginUnusedImports
    },
    settings: {
      react: { version: "detect" }
    },
    rules: {
      ...pluginReact.configs.recommended.rules,

      // ---- Prettier integration ----
      "prettier/prettier": ["error", { endOfLine: "auto" }],

      // ---- TypeScript ----
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/ban-ts-comment": "warn",
      // Same options as the server config: `_`-prefixed identifiers stay, which
      // is what tsconfig's `noUnusedParameters` already allows and what the
      // codebase uses for deliberately-unused callback parameters.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          args: "after-used",
          caughtErrors: "none"
        }
      ],
      // Safe here (unlike on the server, where emitDecoratorMetadata + Nest DI
      // need the runtime import). tsconfig sets `verbatimModuleSyntax`, so
      // type-only imports must be marked anyway.
      "@typescript-eslint/consistent-type-imports": "error",

      // ---- React ----
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      // Only the two rules the source config effectively enabled. Its
      // eslint-plugin-react-hooks was v5; v7's `recommended` preset adds a
      // large set of react-compiler rules that are out of scope for a lint
      // config port.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "off",

      // ---- General JavaScript ----
      "no-undef": "off",
      "prefer-const": "warn",
      "no-var": "error",
      "no-console": "warn",
      "spaced-comment": "error",
      "arrow-body-style": ["error", "as-needed"],

      // ---- Imports ----
      "unused-imports/no-unused-imports": "error",

      // ---- a11y ----
      "jsx-a11y/alt-text": "warn",
      "jsx-a11y/anchor-is-valid": "warn",
      "jsx-a11y/no-autofocus": "warn",

      // ---- Promise ----
      "promise/always-return": "warn",
      "promise/no-return-wrap": "warn",
      "promise/param-names": "warn",
      "promise/catch-or-return": "warn",

      // ---- Pre-existing opt-outs from the TanStack preset ----
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off"
    }
  },
  {
    ignores: [
      "eslint.config.js",
      "prettier.config.js",
      ".worktrees",
      // Playwright E2E + config live outside the typed tsconfig project
      // (excluded so vitest/build ignore them); they are validated by running
      // the suite, not by the typed lint.
      "e2e/**",
      "playwright.config.ts",
      // Generated by `tsr generate`; its own header asks to exclude it from the
      // linter and formatter.
      "src/routeTree.gen.ts"
    ]
  }
];
