/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAiCredentialsRouteImport } from './routes/_app/ai-credentials'
import { Route as AppCvRouteImport } from './routes/_app/cv'
import { Route as AppJdRouteImport } from './routes/_app/jd'
import { Route as AppMyDataRouteImport } from './routes/_app/my-data'
import { Route as AppWizardRouteImport } from './routes/_app/wizard'
import { Route as AppCvRewriteMatchResultIdRouteImport } from './routes/_app/cv-rewrite.$matchResultId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCredentialsRoute = AppAiCredentialsRouteImport.update({
  id: '/ai-credentials',
  path: '/ai-credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppCvRoute = AppCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AppRoute,
} as any)
const AppJdRoute = AppJdRouteImport.update({
  id: '/jd',
  path: '/jd',
  getParentRoute: () => AppRoute,
} as any)
const AppMyDataRoute = AppMyDataRouteImport.update({
  id: '/my-data',
  path: '/my-data',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardRoute = AppWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppCvRewriteMatchResultIdRoute =
  AppCvRewriteMatchResultIdRouteImport.update({
    id: '/cv-rewrite/$matchResultId',
    path: '/cv-rewrite/$matchResultId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai-credentials': typeof AppAiCredentialsRoute
  '/cv': typeof AppCvRoute
  '/jd': typeof AppJdRoute
  '/my-data': typeof AppMyDataRoute
  '/wizard': typeof AppWizardRoute
  '/cv-rewrite/$matchResultId': typeof AppCvRewriteMatchResultIdRoute
}
export interface FileRoutesByTo {
  '/ai-credentials': typeof AppAiCredentialsRoute
  '/cv': typeof AppCvRoute
  '/jd': typeof AppJdRoute
  '/my-data': typeof AppMyDataRoute
  '/wizard': typeof AppWizardRoute
  '/': typeof AppIndexRoute
  '/cv-rewrite/$matchResultId': typeof AppCvRewriteMatchResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-credentials': typeof AppAiCredentialsRoute
  '/_app/cv': typeof AppCvRoute
  '/_app/jd': typeof AppJdRoute
  '/_app/my-data': typeof AppMyDataRoute
  '/_app/wizard': typeof AppWizardRoute
  '/_app/': typeof AppIndexRoute
  '/_app/cv-rewrite/$matchResultId': typeof AppCvRewriteMatchResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-credentials'
    | '/cv'
    | '/jd'
    | '/my-data'
    | '/wizard'
    | '/cv-rewrite/$matchResultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-credentials'
    | '/cv'
    | '/jd'
    | '/my-data'
    | '/wizard'
    | '/'
    | '/cv-rewrite/$matchResultId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ai-credentials'
    | '/_app/cv'
    | '/_app/jd'
    | '/_app/my-data'
    | '/_app/wizard'
    | '/_app/'
    | '/_app/cv-rewrite/$matchResultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-credentials': {
      id: '/_app/ai-credentials'
      path: '/ai-credentials'
      fullPath: '/ai-credentials'
      preLoaderRoute: typeof AppAiCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cv': {
      id: '/_app/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AppCvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jd': {
      id: '/_app/jd'
      path: '/jd'
      fullPath: '/jd'
      preLoaderRoute: typeof AppJdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-data': {
      id: '/_app/my-data'
      path: '/my-data'
      fullPath: '/my-data'
      preLoaderRoute: typeof AppMyDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wizard': {
      id: '/_app/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AppWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cv-rewrite/$matchResultId': {
      id: '/_app/cv-rewrite/$matchResultId'
      path: '/cv-rewrite/$matchResultId'
      fullPath: '/cv-rewrite/$matchResultId'
      preLoaderRoute: typeof AppCvRewriteMatchResultIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiCredentialsRoute: typeof AppAiCredentialsRoute
  AppCvRoute: typeof AppCvRoute
  AppJdRoute: typeof AppJdRoute
  AppMyDataRoute: typeof AppMyDataRoute
  AppWizardRoute: typeof AppWizardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCvRewriteMatchResultIdRoute: typeof AppCvRewriteMatchResultIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCredentialsRoute: AppAiCredentialsRoute,
  AppCvRoute: AppCvRoute,
  AppJdRoute: AppJdRoute,
  AppMyDataRoute: AppMyDataRoute,
  AppWizardRoute: AppWizardRoute,
  AppIndexRoute: AppIndexRoute,
  AppCvRewriteMatchResultIdRoute: AppCvRewriteMatchResultIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
